blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.top_page, name='top_page'),
    path('page_under_construction/', views.page_under_construction, name='page_under_construction'),
    path('create/',views.CreateView.as_view(),name="create"),
    path('index/',views.index, name="index"),
    path('login/', views.loginView.as_view(), name="login"),
    path('logout/', views.logoutView.as_view(), name="logout"),
    # like post
    path('like', views.like, name='like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

"""　ここのURLconfの名前はアプリケーションのblogではないので以下コメントアウト　"""
# app_name= "blog"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('login/', include('blog.urls')),
    path('index/', include('blog.urls')),
]

accounts/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name="author")
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


# class Like(models.Model):
#     created_date = models.DateTimeField(default=timezone.now)
#
#     class Meta:
#         db_table = 'like'
#         verbose_name = verbose_name_plural = 'いいね'

class LikePost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    created_date = models.DateTimeField(default=timezone.now)

blog/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from .models import Post


class LoginForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text',)

accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView

from django.views.generic import TemplateView
from . import forms

appname='blog'





#def index(request):
    #
    #render(request,"blog/index.html",{'posts': posts})

blog/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView as cf
from django.urls import reverse_lazy
from .models import Post, LikePost  # Like
from .forms import LoginForm as r
from .forms import PostForm

app_name='blog'


def top_page(request):
    return render(request, 'blog/top_page.html', {})


def page_under_construction(request):
    return render(request, 'blog/page_under_construction.html', {})


class loginView(LoginView):
    form_class = r
    template_name = "blog/login.html"
    reverse_lazy('login')


class logoutView(LoginRequiredMixin, LogoutView):
    template_name = "blog/logout.html"


@login_required
def index(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #post.published_date = timezone.now()
            post.save()
            # ここで一気に集計テーブルへもデータを埋め込みます
            s = LikePost.objects.create(post_id=post.id, count=0)
            s.save()
    else:
        form = PostForm()

    """ 
        like_count = LikePost.objects.count() 
        これはレコード数すべてをカウントします。
        方法はいくつかありますが、ここでは集計テーブルとしてLIKEを使用してみましょう。
        LIKEされる都度、集計データを更新します。likeメソッドを確認してください。
        これで、外部結合をしてデータを取ってきます。
        SELECT * FROM `blog_post`AS p LEFT JOIN blog_likepost AS l ON p.id=L.post_id
        
    """
    # like_count = LikePost.objects.count(post__id)
    # posts = Post.objects.order_by('-created_date')[:5]
    posts = Post.objects.select_related('likepost').values('likepost__count',
                                                           'text',
                                                           'created_date',
                                                           'title',
                                                           'id').order_by('-created_date')[:5]
    return render(request,'blog/index.html', {'posts':posts, 'form':form})


class CreateView(cf):
    form_class = UserCreationForm
    template_name = "blog/create.html"
    success_url = reverse_lazy("blog:login")


@login_required
def like(requests):
    if requests.method == 'POST':
        statue = LikePost.objects.filter(post_id=requests.POST['post_id']).first()
        if LikePost.objects.filter(post_id=requests.POST['post_id']).exists():
            statue.count += 1
            statue.save()
        else:
            s = LikePost.objects.create(post_id = requests.POST['post_id'], count=1)
            s.save()
        # LikePost.objects.create()
    return redirect('blog:index')

blog/templates/blog/base.html
<!-- ▼▼▼ git commit ”ログインユーザー改修”　テンプレートの拡張機能を搭載しました　▼▼▼-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>LOGIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ▼▼▼ bootstrap搭載　▼▼▼-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- ▲▲▲ Bootstrap搭載　▲▲▲-->
    <!-- ▼▼▼ original搭載　▼▼▼-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- ▲▲▲ original搭載　▲▲▲-->
</head>

    {% block loginForm %}{%  endblock %}
</body>
</html>
<!-- ▲▲▲ git commit ”ログインユーザー改修”　テンプレートの拡張機能を搭載しました　▲▲▲-->

blog/templates/blog/create.html
<!-- ▼▼▼ git commit ”ログインユーザー改修”　テンプレートの拡張機能を搭載しました　▼▼▼-->
<!--1.　まずは親テンプレートを指定します。-->
{% extends 'blog/base.html' %}
<!--2. 次に親テンプレートに組み込むブロックを記述します-->
    {%  block loginForm %}
    <p>新規ユーザーの作成</p>
    <form action="{% url 'blog:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">作成</button>
    </form>
    <a href="{% url 'blog:login' %}"><button type="button" class="btn btn-outline-info">ログイン画面へ</button></a>
    {% endblock %}
<!-- ▲▲▲ git commit ”ログインユーザー改修”　テンプレートの拡張機能を搭載しました　▲▲▲-->

blog/templates/blog/index.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <h1>好きなことをつぶやこう！</h1>
    <i class="fas fa-dove"></i>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">つぶやく</button>
    </form>
    <p>タイムライン</p>
    <p><a href="{% url 'blog:page_under_construction' %}">マイページ</a></p>
    <!--        以下、postsがデータを所持しているかどうかを判定して、条件分岐をさせています。-->

        {% for post in posts %}
        <div style="border: 1px solid;">
            <div>
                <p>投稿日: {{ post.created_date }}</p>
                <h1><a href="">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaksbr }}</p>
             </div>
            <br>
                <form action="/like" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ post.id }}" name="post_id">
                        <input type="hidden" value="{{ post.author_id }}" name="user_id">
                       <input type="submit" name="like" value="いいね">（この投稿に{{ post.likepost__count }} 件いいねされました。）
                </form>
        </div>
        {% endfor %}

    <a href="{% url 'blog:top_page' %}">ログアウト</a>
</body>

blog/templates/blog/login.html
<!-- ▼▼▼ git commit ”ログインユーザー改修”　テンプレートの拡張機能を搭載しました　▼▼▼-->
<!--1.　まずは親テンプレートを指定します。-->
{% extends 'blog/base.html' %}
<!--2. 次に親テンプレートに組み込むブロックを記述します-->
<!--拡張元のbase.htmlとブロック名が異なるので真っ白の画面になってしました。こちらを対応-->
    {%  block loginForm %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="blog:index"><button type="submit">ログイン</button></a>
    </form>
<!--    git commit ”ログインユーザー改修”　ユーザーを作成する画面はDjangoでは別途作成する必要があるのでformタグの外に置きました-->
    <a href="{% url 'blog:create' %}"><button type="button" class="btn btn-outline-info">ユーザー作成</button></a>
    {% endblock %}
<!-- ▲▲▲ git commit ”ログインユーザー改修”　テンプレートの拡張機能を搭載しました　▲▲▲-->

blog/templates/blog/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<form action="" method="POST">
{% csrf_token %}
<button type="submit">ログアウト</button>
</form>
</body>
</html>

blog/templates/blog/page_under_construction.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>page under construction</title>
</head>
<body>
page under construction
</body>
</html>

blog/templates/blog/top_page.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>top_page</title>
</head>
  <body>
  <h1><a href="/">つぶやき君にようこそ！</a></h1>
   <a href="{% url 'blog:login'  %}">ログインページ</a>
  </body>
</html>